spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/itLeansDb"
    username: "postgres"
    password: "@@root@"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        show_sql_comment: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect